# General Settings
name: Thomas ILLIET
job_title: Consultant Cloud et Infrastructure
email: contact@thomas-illiet.fr
description: n/a
avatar: /assets/img/avatar.png
favicon: /favicon.ico
twitter_handler: thomas-illiet
analytics_code: UA-XXXXXXX-2
disqus: thomas-illiet

# Social Accounts
social_networks:
-  { name: twitter, url: 'https://twitter.com/thomas_illiet' }
-  { name: linkedin, url: 'https://www.linkedin.com/in/thomas-illiet/' }
-  { name: github, url: 'https://github.com/thomas-illiet' }
-  { name: spotify, url: 'https://open.spotify.com/user/thomas-illiet?si=I5pld98gQw6Qvog4yqoZ-Q' }

# Modules Settings
show_categories: 1
show_tags: 1
show_email: 0
show_rss: 1
show_comments: 1
show_menu: 1
fixed_sidebar: 1

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      comments: true

# Serving
url: "https://thomas-illiet.github.io/"
baseurl: ""

# Includes
include: ["_pages"]

# Outputting
permalink: /:categories/:year/:month/:day/:title:output_ext
category_dir: categories

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Conversion
markdown: kramdown
lsi: false
excerpt_separator: <!--more-->
incremental: false
highlighter: rouge

# kramdown configuration
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Do not publish future posts
future: false

# Assets Settings
sass:
  sass_dir: assets/partials
